# Generated by Django 3.2.6 on 2022-02-20 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDishModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deatil', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('discounted', models.FloatField()),
                ('availablity', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='pictures')),
                ('ingredients', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AddToFevorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_name', to='tiffine_site.maindishmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fevorate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
