# Generated by Django 3.2.6 on 2022-03-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0007_alter_commentandrating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentandrating',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
