# Generated by Django 3.2.6 on 2022-03-09 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0008_alter_commentandrating_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentandrating',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tiffine_site.maindishmodel'),
        ),
    ]
