# Generated by Django 3.2.6 on 2022-03-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0011_auto_20220311_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
