# Generated by Django 3.2.6 on 2022-03-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0013_alter_phonenumber_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
