# Generated by Django 3.2.6 on 2022-03-15 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0014_auto_20220314_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='items',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='item_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_1', to='tiffine_site.maindishmodel'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='item_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_2', to='tiffine_site.maindishmodel'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='item_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_3', to='tiffine_site.maindishmodel'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='item_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_4', to='tiffine_site.maindishmodel'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='item_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_5', to='tiffine_site.maindishmodel'),
        ),
    ]
