# Generated by Django 3.2.6 on 2022-03-16 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0016_auto_20220316_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='qyt_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qyt_1', to='tiffine_site.cart'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='qyt_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qyt_2', to='tiffine_site.cart'),
        ),
    ]
