# Generated by Django 3.2.6 on 2022-03-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0017_auto_20220316_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='qyt_1',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='qyt_2',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
