# Generated by Django 3.2.6 on 2022-03-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0019_auto_20220317_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='qyt_1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='qyt_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='qyt_3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='qyt_4',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='qyt_5',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
